name: Build DownloadAssistant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      '6.8.2'
        host:         'windows'
        target:       'desktop'
        arch:         'win64_msvc2022_64'
        modules:      'qtcharts qtnetworkauth qtmultimedia'
        install-deps: true
        dir:          'C:/Qt'
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install libsmbclient
      shell: powershell
      run: |
        git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
        & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat"
        & "$env:VCPKG_ROOT\vcpkg" install libsmbclient:x64-windows
        echo "INCLUDE=$env:VCPKG_ROOT\installed\x64-windows\include;$env:INCLUDE" >> $env:GITHUB_ENV
        echo "LIB=$env:VCPKG_ROOT\installed\x64-windows\lib;$env:LIB" >> $env:GITHUB_ENV
    
    - name: Configure
      shell: cmd
      run: |
        set PATH=C:\Qt\6.8.2\msvc2022_64\bin;%PATH%
        qmake
        
    - name: Build
      shell: cmd
      run: |
        nmake
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DownloadAssistant
        path: |
          release/*.exe
          release/*.dll
        retention-days: 30 